# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4daca5626b1cbcd18efa008591cfe7e0d0ed4d23b140a35162e82fdf74ec102aca044626750a433770a28866ab1915288a0192e51af920d7d71e85a7528a4d58

test:
  secret_key_base: 372d414e5b8139dde40ec2413de3b1c6d1793ca28fb0a8f7fca44d320917e362e5fd048c256dd2a17125e51ad65e0682a4f7ab553574c45849b9764c78334585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
